# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [48]:
import numpy as np

In [ ]:
# ejercicio 1 Dado el arreglo a = np.array([1, 2, 3, 4]), determina si ninguno de los elementos es cero.
a = np.array([1, 2, 3, 4])
resultado = np.all(a != 0)  
print(resultado)  

True


In [ ]:
# ejercicio 2 Dado el arreglo a = np.array([0, 0, 2, 0]), determina si contiene algún elemento que no sea cero.
a = np.array([0, 0, 2, 0])
resultado = np.any(a != 0)
print(resultado)  

True


In [24]:
# ejercicio 3 
# Analiza el arreglo a = np.array([1, 2, np.nan, np.inf]) y 
# determina si contiene valores que sean infinitos o valores no numéricos (NaN).
a = np.array([1, 2, np.nan, np.inf])

# 1. Verificar si contiene infinitos (positivos o negativos)
tiene_inf = np.any(np.isinf(a))
print("¿Contiene infinitos?:", tiene_inf)  

# 2. Verificar si contiene NaN
tiene_nan = np.any(np.isnan(a))
print("¿Contiene NaN?:", tiene_nan)  



¿Contiene infinitos?: True
¿Contiene NaN?: True


In [26]:
# ejercicio 4 Dado el arreglo a = np.array([1, 2, np.inf]), determina si contiene valores infinitos.
a = np.array([1, 2, np.inf])
tiene_inf = np.any(np.isinf(a))
print("¿Contiene infinitos?:", tiene_inf)  

¿Contiene infinitos?: True


In [27]:
# ejercicio 5 Dado el arreglo a = np.array([1, np.nan, 3]), determina si contiene valores NaN.

a = np.array([1, np.nan, 3])
tiene_nan = np.any(np.isnan(a))
print("¿Contiene NaN?:", tiene_nan)


¿Contiene NaN?: True


In [30]:
# ejercicio 6 Dados los arreglos a = np.array([1, 3, 5]) y b = np.array([2, 3, 4]), realiza una comparación elemento a elemento 
# contemplando mayor, mayor o igual, menor y menor o igual.

a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

print("Mayor:", a > b)
print("Mayor o igual:", a >= b)
print("Menor:", a < b)
print("Menor o igual:", a <= b)

Mayor: [False False  True]
Mayor o igual: [False  True  True]
Menor: [ True False False]
Menor o igual: [ True  True False]


In [31]:
# ejercicio 7 Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
arreglo = np.array([1, 7, 13, 105])
print("Memoria ocupada (bytes):", arreglo.nbytes)

Memoria ocupada (bytes): 32


In [32]:
# ejercicio 8 Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10, 5)
print("Arreglo de ceros:", ceros)
print("Arreglo de unos:", unos)
print("Arreglo de cincos:", cincos)


Arreglo de ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Arreglo de unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Arreglo de cincos: [5 5 5 5 5 5 5 5 5 5]


In [33]:
# ejercicio 9 Crea un arreglo que contenga todos los números enteros entre 30 y 70.
arreglo = np.arange(30, 71)
print(arreglo)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [34]:
# ejercicio 10 Crea un arreglo que contenga los números pares entre 30 y 70.
arreglo_pares = np.arange(30, 71, 2)
print(arreglo_pares)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [35]:
# ejercicio 11 Crea una matriz identidad de 3x3.
matriz_identidad = np.identity(3)
print(matriz_identidad)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# ejercicio 12 Genera un número aleatorio entre 0 y 1.
numero_aleatorio = np.random.rand()
print(numero_aleatorio)


0.5677161282337474


In [37]:
# ejercicio 13 Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
arreglo_aleatorio = np.random.randn(15)
print(arreglo_aleatorio)


[ 0.06762684 -2.09333595  0.24384118  0.16762745 -0.81418589 -1.67530738
 -0.35829355  0.4044212  -1.45411873 -0.01692527 -0.61160055 -0.91116255
  1.36262837 -1.26691526  0.70642321]


In [38]:
# ejercicio 12 Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
arreglo = np.arange(15, 56)
print(arreglo[1:-1])  # Imprime todos los elementos excepto el primero y el último


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [39]:
# ejercicio 13 Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
vector = np.linspace(5, 50, 10)
print(vector)


[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [41]:
# ejercicio 16 Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
vector = np.arange(21)
vector = np.where((vector >= 9) & (vector <= 15), -vector, vector)
print(vector)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [43]:
# ejercicio 17 Convierte el arreglo a = np.array([1, 2, 3]) a una lista de Python.
a = np.array([1, 2, 3])
b = a.tolist()

print("Tipo:", type(a))
print("Tipo:", type(b))

Tipo: <class 'numpy.ndarray'>
Tipo: <class 'list'>


In [ ]:
# ejercicio 18 Convierte la lista l = [1, 2, 3] a un arreglo de Numpy.
l = [1, 2, 3]
a = np.array(l)
print("Tipo:", type(l))
print("Tipo:", type(a))

Tipo: <class 'list'>
Tipo: <class 'numpy.ndarray'>


In [46]:
# ejercicio 19 Dada la matriz m = np.array([[1, 2], [3, 4]]), verifica qué números son pares y almacena los resultados en otra matriz.
a = np.array([[1, 2], [3, 4]])
pares = (a % 2 == 0)
print(pares)

# alternativa
resultado_str = np.where(a % 2 == 0, "Par", "Impar")
print("\nMatriz con strings:")
print(resultado_str)



[[False  True]
 [False  True]]

Matriz con strings:
[['Impar' 'Par']
 ['Impar' 'Par']]


In [47]:
# ejercicio 20 Dado el arreglo m = np.array([[1, 2, 3], [4, 5, 6]]), encuentra el número de filas y columnas de la matriz.
m = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m.shape
print("Número de filas:", filas)
print("Número de columnas:", columnas)


Número de filas: 2
Número de columnas: 3
